version: "3.8"

services:
  systemservice:
    build:
      context: ./SystemService
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: systemservice
    ports:
      - "8000:8000"
    depends_on:
      - database
    networks:
      - app-network

  userservice:
    build:
      context: ./UsersService
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: userservice
    ports:
      - "6050:6050"
    depends_on:
      - database
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - systemservice
      - database
    networks:
      - app-network

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile

    container_name: ui
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  database:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - ui
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
